# Generated by Django 3.0.3 on 2020-02-11 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='', max_length=100)),
                ('blood_group', models.CharField(choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'A -ve'), ('A1 +ve', 'A1 +ve'), ('A1 -ve', 'A1 -ve'), ('A2 +ve', 'A2 +ve'), ('A2 -ve', 'A2 -ve'), ('A1B +ve', 'A1B +ve'), ('A1B -ve"', 'A1B -ve"'), ('A2B +ve', 'A2B +ve'), ('A2B -ve"', 'A2B -ve"'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve')], default=' ', max_length=10)),
                ('donor_std', models.CharField(max_length=3)),
                ('donor_zip', models.CharField(max_length=6)),
                ('donor_phone', models.CharField(max_length=10)),
                ('donor_email', models.EmailField(max_length=254, unique=True)),
                ('donor_pass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DonorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_phone', models.CharField(max_length=10)),
                ('req_reply', models.CharField(max_length=50)),
                ('req_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('donors_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibd.Donor')),
            ],
            options={
                'ordering': ['req_phone'],
            },
        ),
    ]
